# rtl-buddy
# vim: set sw=2:ts=2:et:
#
# Copyright 2024 rtl_buddy contributors
#
"""
vlog_filelist module handles verilog filelist processing for rtl-buddy
"""

import logging

logger = logging.getLogger(__name__)
from ..errors import FilelistError
from ..logging_utils import log_event
import os.path
import re


class VlogFilelist:
    """
    Verilog Filelist Parser and Builder
    """

    def __init__(self, name, model_cfg, output_path):
        self.name = name
        self.output_path = output_path
        # model_cfg may be None for callers that drive a multi-model
        # generation flow (e.g. write_verible_filelist) and supply
        # the models per call.
        self.model_cfg = model_cfg

    def _fail(self, event, message, **fields):
        log_event(logger, logging.ERROR, event, **fields)
        raise FilelistError(message)

    def _extract(self, lines_in, unroll, fpath):
        """
        Get the lines of a .f file, recursively following -F includes if unroll is True.
        Prepends prefix to all paths from recursive calls.
        Returns a list of (full_path, option) tuples, in order.
        """
        prefix_parent = os.path.dirname(fpath)
        entries = []
        libexts = set()
        for line in lines_in:
            line = line.strip()
            if (
                not line
                or line.startswith("//")
                or line.startswith("/*")
                or line.startswith("*")
            ):
                # logger.info(f'{fpath}: Skipping line due to comment: "{line}"')
                continue

            # Generated by AI
            pattern = re.compile(
                r"""^
        (                           # group 1: option, or empty
          (?:-v|                    # '-v'
           -y|         		          # '-y'
           -[Ff])\s+                # '-F' or '-f' (case sensitive) + space(s)
          |                         # OR
          (\+(?:
            incdir|									# '+incdir+'
            libext									# '+libext+'
					)\+))             
        ?                           # group 1 optional, so path only works
        (.*)                        # group 3: the path part (required)
        $""",
                re.VERBOSE,
            )

            m = pattern.fullmatch(line)

            if not m or not m.group(3):
                self._fail(
                    "filelist.malformed_line",
                    f'{fpath}: malformed filelist line "{line}"',
                    file=fpath,
                    line=line,
                )

            # Determine which style matched, return (option, path)
            if m.group(2):  # +incdir+, +libext+
                line_option = m.group(2)
                line_path = m.group(3)
            elif m.group(1):  # -v, -F, -f, -y
                line_option = (
                    m.group(1).strip() + " "
                )  # Add a space since +incdir+ does not have a space behind
                line_path = m.group(3)
            else:
                line_option = None
                line_path = m.group(3)

            # logger.debug(f'Read line: {line_option}{line_path}')
            # Parse option
            line_path = os.path.expandvars(line_path)
            if line_option == "-f ":
                log_event(
                    logger,
                    logging.ERROR,
                    "filelist.inline_f_disallowed",
                    file=fpath,
                    line=line,
                )
                raise FilelistError(
                    f'{fpath}: -f not allowed. Found in file {fpath} line: "{line}"'
                )

            elif line_option == "-F " and unroll:  # Recurse if unroll
                path_next = os.path.join(prefix_parent, line_path)  # path of next file
                # logger.debug(f'{fpath}: Recursively opening "{path_next}"')
                try:
                    with open(path_next, "r") as f:
                        lines_next = f.readlines()
                        extracted_next = self._extract(lines_next, unroll, path_next)
                        entries.extend(extracted_next)
                except FileNotFoundError:
                    self._fail(
                        "filelist.include_missing",
                        f'{fpath}: included file "{path_next}" not found',
                        file=fpath,
                        include=path_next,
                    )

            elif line_option == "+libext+":  # +libext+ isn't actually a path
                libexts.update(line_path.split("+"))

            else:  # Base case. Handles -v, source lines, and -F if not unroll
                out_path = os.path.join(prefix_parent, line_path)
                entries.append((out_path, line_option))

        # Consolidate all +libext+ into a single entry
        if len(libexts) != 0:
            entries.append(("+".join(libexts), "+libext+"))

        return entries

    def _process(
        self, entries, output_dir, flatten=False, strip=False, deduplicate=False
    ):
        """Do flatten, strip, and deduplicate after all lines are collected at the top level."""
        output_dir = os.path.abspath(output_dir)
        out_lines = []
        for line_path, line_option in entries:
            resolved_line_path = os.path.normpath(os.path.join(output_dir, line_path))
            line_path = os.path.relpath(
                resolved_line_path, start=output_dir
            )  # simplifies path relative to the filelist location
            # File or dir exists check
            if line_option == "+incdir+" or line_option == "-y ":
                if not os.path.isdir(resolved_line_path):
                    self._fail(
                        "filelist.directory_missing",
                        f"{line_path} is not a directory",
                        path=line_path,
                    )
            elif line_option != "+libext+":
                if not os.path.isfile(resolved_line_path):
                    self._fail(
                        "filelist.source_missing",
                        f"{line_path} file does not exist",
                        path=line_path,
                    )

            if flatten:
                line_path = os.path.basename(line_path)

            if strip:
                line_option = ""

            line = f"{line_option}{line_path}\n" if line_option else f"{line_path}\n"
            if deduplicate:
                if line in out_lines:
                    # logger.info(f'Duplicate detected, discarding: "{line_option or ""}{line_path}"')
                    continue

            # logger.debug(f'Post-proc: "{line_option}{line_path}"')
            out_lines.append(line)

        return out_lines

    def write_output(
        self,
        output_filepath=None,
        unroll=False,
        flatten=False,
        strip=False,
        deduplicate=False,
        test_filelist=None,
        suite_dir=None,
    ):
        if output_filepath is None:
            output_filepath = self.output_path
        log_event(logger, logging.DEBUG, "filelist.write_start", output=output_filepath)

        # Get filelist from models
        model_filelist = self.model_cfg.get_filelist()
        entries = self._extract(
            model_filelist, unroll, os.path.abspath(self.model_cfg.get_model_path())
        )

        # Get filelist from tests. Entries are declared relative to the
        # suite config's directory (tests.yaml). Use suite_dir when the
        # caller supplies it; fall back to cwd for callers that still
        # assume the legacy "process cwd is the suite dir" model.
        if test_filelist:
            suite_anchor = (
                os.path.abspath(suite_dir) if suite_dir else os.path.abspath(".")
            )
            entries.extend(
                self._extract(
                    test_filelist,
                    unroll,
                    os.path.join(suite_anchor, "tests.yaml"),
                )
            )

        lines = self._process(
            entries,
            output_dir=os.path.dirname(output_filepath) or ".",
            flatten=flatten,
            strip=strip,
            deduplicate=deduplicate,
        )

        with open(output_filepath, "w") as f:
            f.write("// rtl-buddy generated model filelist\n")
            f.writelines(lines)
            log_event(
                logger, logging.INFO, "filelist.write_done", output=output_filepath
            )
        return

    def write_verible_filelist(self, model_cfgs, output_filepath=None):
        """Generate a verible.filelist from one or more ModelConfigs.

        Verible-verilog-ls parses the filelist via
        ``verilog-filelist.cc::AppendFileListFromContent`` which honours
        only bare source-file paths and ``+incdir+`` / ``+define+``
        directives — any other ``+``/``-`` line is silently ignored.
        We strip ``-v`` / ``-y`` / ``+libext+`` here so the on-disk
        filelist only carries lines that affect the LSP's symbol scope.
        ``-F`` chains are always unrolled so the output is a flat list
        the LSP can consume without further indirection.
        """
        if output_filepath is None:
            output_filepath = self.output_path
        log_event(
            logger,
            logging.DEBUG,
            "verible_filelist.write_start",
            output=output_filepath,
            models=[m.name for m in model_cfgs],
        )

        if not model_cfgs:
            self._fail(
                "verible_filelist.no_models",
                "no models supplied for verible filelist generation",
            )

        entries = []
        for cfg in model_cfgs:
            entries.extend(
                self._extract(
                    cfg.get_filelist(),
                    unroll=True,
                    fpath=os.path.abspath(cfg.get_model_path()),
                )
            )

        filtered = [
            (path, opt) for path, opt in entries if opt is None or opt == "+incdir+"
        ]
        lines = self._process(
            filtered,
            output_dir=os.path.dirname(output_filepath) or ".",
            flatten=False,
            strip=False,
            deduplicate=True,
        )

        with open(output_filepath, "w") as f:
            f.write("// rtl-buddy generated verible filelist\n")
            f.writelines(lines)
        log_event(
            logger,
            logging.INFO,
            "verible_filelist.write_done",
            output=output_filepath,
            entries=len(lines),
        )
        return
